<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55d4f27d86090',
	'title' => 'Page Header',
	'fields' => array (
		array (
			'key' => 'field_560eb8b550a4b',
			'label' => 'Header Type',
			'name' => 'header_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'bg-img' => 'Background Image',
				'bg-vid' => 'Background Video',
				'slider' => 'Slider',
				'color' => 'Solid Color',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f6f9499138a',
			'label' => 'Video MP4',
			'name' => 'video_mp4',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-vid',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.mp4',
		),
		array (
			'key' => 'field_55f6f9b99138b',
			'label' => 'Video OGG',
			'name' => 'video_ogg',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-vid',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.ogg, .ogv',
		),
		array (
			'key' => 'field_55f6f9d79138c',
			'label' => 'Video WEBM',
			'name' => 'video_webm',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-vid',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.webm',
		),
		array (
			'key' => 'field_55f6f9ee9138d',
			'label' => 'Video Placeholder Image',
			'name' => 'video_placeholder_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-vid',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_560eb88d9508e',
			'label' => 'Slider Shortcode',
			'name' => 'slider_shortcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d4f30fa518e',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-img',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => 'field_type-image field_key-field_55d4f30fa518e',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5627dce3b2838',
			'label' => 'Background Image color overlay',
			'name' => 'background_image_color_overlay',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-img',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_5627dcfcb2839',
			'label' => 'Background Image color overlay opacity',
			'name' => 'background_image_color_overlay_opacity',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'bg-img',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 1,
			'step' => '0.05',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5627dc7e0759c',
			'label' => 'Header Color',
			'name' => 'header_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '==',
						'value' => 'color',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array (
			'key' => 'field_55f7084decf3b',
			'label' => 'Header Item Direction',
			'name' => 'header_item_direction',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '!=',
						'value' => 'Slider',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'row' => 'Align items horizontally',
				'column' => 'Align items vertically',
			),
			'default_value' => array (
				'column' => 'Align items vertically',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f70875ecf3c',
			'label' => 'Header Item Distribution',
			'name' => 'header_item_distribution',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '!=',
						'value' => 'Slider',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'center' => 'Align items in the center',
				'start' => 'Align items to the top or left',
				'end' => 'Align items to the bottom or right',
				'space-between' => 'Distribute items evenly along the row with no space at the ends',
				'space-around' => 'Distribute items evenly along the row with space at the ends',
			),
			'default_value' => array (
				'center' => 'Align items in the center',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f708d7ecf3d',
			'label' => 'Header Item Alignment',
			'name' => 'header_item_alignment',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '!=',
						'value' => 'Slider',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'center' => 'Align items vertically centered',
				'start' => 'Align items to the top or left',
				'end' => 'Align items to the bottom or right',
				'stretch' => 'Make all items the same height or width',
			),
			'default_value' => array (
				'center' => 'Align items vertically centered',
				'start' => 'Align items to the top or left',
				'end' => 'Align items to the bottom or right',
				'stretch' => 'Make all items the same height or width',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f706c4ecf36',
			'label' => 'Header Content',
			'name' => 'header_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_560eb8b550a4b',
						'operator' => '!=',
						'value' => 'Slider',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => 1,
			'max' => 9,
			'layouts' => array (
				array (
					'key' => '55f706cdddb9d',
					'name' => 'header_text',
					'label' => 'Header text',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55f706d1ecf37',
							'label' => 'Header Text',
							'name' => 'header_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_55f707acecf38',
							'label' => 'Text Color',
							'name' => 'text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55f7080becf39',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55f70810ecf3a',
							'label' => 'Header Image',
							'name' => 'header_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'position',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
	),
	'active' => 1,
	'description' => '',
));

endif;